

  server:
    port: 8081
  spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/toledo96/microservicio
            default-label: config-serve
            search-paths: config-data
    application:
      name: config-service
