

  server:
    port: 8081
  spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/toledo96/microservicio
            username: toledo96
            password: contagiate01
            default-label: config-serve
            searchPaths: config-data
    application:
      name: config-service
